### ISSUE TITLE
CrystalAura rewrite crashes

### ISSUE THREAD

**Issue by master7720** [KassuK1/BlackOut#21]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-04-25 19:30:50
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_2338.<init>(net.minecraft.class_243)'
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.getPlacePos(AutoCrystalRewrite.java:1358)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.updatePlacement(AutoCrystalRewrite.java:1129)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.update(AutoCrystalRewrite.java:999)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.onRender3D(AutoCrystalRewrite.java:802)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_757.handler$zmj000$meteor-client$onRenderWorld(class_757.java:1644)
	at net.minecraft.class_757.method_3188(class_757.java:1124)
	at net.minecraft.class_757.method_3192(class_757.java:872)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.getPlacePos(AutoCrystalRewrite.java:1358)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.updatePlacement(AutoCrystalRewrite.java:1129)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.update(AutoCrystalRewrite.java:999)
	at kassuk.addon.blackout.modules.AutoCrystalRewrite.onRender3D(AutoCrystalRewrite.java:802)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:47)
	at net.minecraft.class_757.handler$zmj000$meteor-client$onRenderWorld(class_757.java:1644)
	at net.minecraft.class_757.method_3188(class_757.java:1124)

-- Affected level --
Details:
	All players: 13 total; [class_746['Master7720'/328728, l='ClientLevel', x=7.74, y=109.38, z=16.70], class_745['help_desk_npc'/265, l='ClientLevel', x=-32.49, y=131.00, z=10.49], class_745['soon_5'/225, l='ClientLevel', x=34.46, y=133.00, z=8.47], class_745['soon_4'/233, l='ClientLevel', x=35.53, y=133.00, z=3.47], class_745['snowiestEar245'/325768, l='ClientLevel', x=9.50, y=2.00, z=32.50], class_745['soon_1'/241, l='ClientLevel', x=34.50, y=133.00, z=-7.51], class_745['soon_3'/257, l='ClientLevel', x=35.48, y=133.00, z=0.47], class_745['Mama_Y1_Jaba'/240381, l='ClientLevel', x=20.62, y=131.00, z=15.60], class_745['soon_2'/249, l='ClientLevel', x=35.51, y=133.00, z=-2.50], class_745['RedCarlos26'/323113, l='ClientLevel', x=11.01, y=131.00, z=19.89], class_745['heedii'/326582, l='ClientLevel', x=9.43, y=2.00, z=32.70], class_745['xps_fnx'/329717, l='ClientLevel', x=0.36, y=131.00, z=8.99], class_745['cuteMonkeys'/325074, l='ClientLevel', x=0.00, y=131.00, z=0.00]]
	Chunk stats: 1024, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,131,0), Section: (at 0,3,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1748534410 game time, 1000 day time
	Server brand: Crystal (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods

**Comment by master7720** [comment]
im using the lastest dev version of black and meteor and using the lastest stable version of sodium,lithium and starlight.

**Comment by OLEPOSSU** [comment]
blackout is for 1.19.3

**Comment by 0xSharkyy** [comment]
> ---- Minecraft Crash Report ---- // Daisy, daisy...
> 
> Time: 2023-04-25 19:30:50 Description: Unexpected error
> 
> java.lang.NoSuchMethodError: 'void net.minecraft.class_2338.(net.minecraft.class_243)' at kassuk.addon.blackout.modules.AutoCrystalRewrite.getPlacePos(AutoCrystalRewrite.java:1358) at kassuk.addon.blackout.modules.AutoCrystalRewrite.updatePlacement(AutoCrystalRewrite.java:1129) at kassuk.addon.blackout.modules.AutoCrystalRewrite.update(AutoCrystalRewrite.java:999) at kassuk.addon.blackout.modules.AutoCrystalRewrite.onRender3D(AutoCrystalRewrite.java:802) at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) at meteordevelopment.orbit.EventBus.post(EventBus.java:47) at net.minecraft.class_757.handler$zmj000$meteor-client$onRenderWorld(class_757.java:1644) at net.minecraft.class_757.method_3188(class_757.java:1124) at net.minecraft.class_757.method_3192(class_757.java:872) at net.minecraft.class_310.method_1523(class_310.java:1218) at net.minecraft.class_310.method_1514(class_310.java:801) at net.minecraft.client.main.Main.main(Main.java:237) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head -- Thread: Render thread Stacktrace: at kassuk.addon.blackout.modules.AutoCrystalRewrite.getPlacePos(AutoCrystalRewrite.java:1358) at kassuk.addon.blackout.modules.AutoCrystalRewrite.updatePlacement(AutoCrystalRewrite.java:1129) at kassuk.addon.blackout.modules.AutoCrystalRewrite.update(AutoCrystalRewrite.java:999) at kassuk.addon.blackout.modules.AutoCrystalRewrite.onRender3D(AutoCrystalRewrite.java:802) at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83) at meteordevelopment.orbit.EventBus.post(EventBus.java:47) at net.minecraft.class_757.handler$zmj000$meteor-client$onRenderWorld(class_757.java:1644) at net.minecraft.class_757.method_3188(class_757.java:1124)
> 
> -- Affected level -- Details: All players: 13 total; [class_746['Master7720'/328728, l='ClientLevel', x=7.74, y=109.38, z=16.70], class_745['help_desk_npc'/265, l='ClientLevel', x=-32.49, y=131.00, z=10.49], class_745['soon_5'/225, l='ClientLevel', x=34.46, y=133.00, z=8.47], class_745['soon_4'/233, l='ClientLevel', x=35.53, y=133.00, z=3.47], class_745['snowiestEar245'/325768, l='ClientLevel', x=9.50, y=2.00, z=32.50], class_745['soon_1'/241, l='ClientLevel', x=34.50, y=133.00, z=-7.51], class_745['soon_3'/257, l='ClientLevel', x=35.48, y=133.00, z=0.47], class_745['Mama_Y1_Jaba'/240381, l='ClientLevel', x=20.62, y=131.00, z=15.60], class_745['soon_2'/249, l='ClientLevel', x=35.51, y=133.00, z=-2.50], class_745['RedCarlos26'/323113, l='ClientLevel', x=11.01, y=131.00, z=19.89], class_745['heedii'/326582, l='ClientLevel', x=9.43, y=2.00, z=32.70], class_745['xps_fnx'/329717, l='ClientLevel', x=0.36, y=131.00, z=8.99], class_745['cuteMonkeys'/325074, l='ClientLevel', x=0.00, y=131.00, z=0.00]] Chunk stats: 1024, 201 Level dimension: minecraft:overworld Level spawn location: World: (0,131,0), Section: (at 0,3,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) Level time: 1748534410 game time, 1000 day time Server brand: Crystal (Velocity) Server type: Non-integrated multiplayer server Stacktrace: at net.minecraft.class_638.method_8538(class_638.java:455) at net.minecraft.class_310.method_1587(class_310.java:2406) at net.minecraft.class_310.method_1514(class_310.java:825) at net.minecraft.client.main.Main.main(Main.java:237) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
> 
> -- Last reload -- Details: Reload number: 1 Reload reason: initial Finished: Yes Packs: vanilla, Fabric Mods

it looks like your client has some sort of error with updating the attack speed and damage? i dont know what is causing this, possibly could be the mods that you have being incompatible with the updates that the addon is trying to give or provide
