### ISSUE TITLE
Future + Meteor + BlackOut = Crash

### ISSUE THREAD

**Issue by slmpc** [KassuK1/BlackOut#48]
Future + Meteor + BlackOut = Crash

```
[21:46:27] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[21:46:28] [main/INFO]: Loading 80 mods:
	- blackout 1.0.1
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.0+kotlin.1.9.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.21.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.2
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- future 1.0
	- iris 1.6.7
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- kappa 0.1.0
	- meteor-client 0.5.4-1907
	   \-- baritone-meteor 1.20.1-SNAPSHOT
	- minecraft 1.20.1
	- reeses-sodium-options 1.6.4+mc1.20.1-build.94
	- sodium 0.5.1
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
[21:46:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/E:/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[21:46:29] [main/INFO]: Compatibility level set to JAVA_17
[21:46:33] [main/WARN]: Reference map 'kappa-refmap.json' for kappa.mixins.json could not be read. If this is a development environment you can ignore this message
[21:46:33] [main/INFO]: Loaded configuration file for Sodium: 41 options available, 3 override(s) found
[21:46:33] [main/INFO]: Loaded configuration file for Sodium Extra: 32 options available, 0 override(s) found
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:46:35] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[21:46:39] [main/WARN]: Error loading class: com/llamalad7/mixinextras/MixinExtrasBootstrap::init (java.lang.ClassNotFoundException: com/llamalad7/mixinextras/MixinExtrasBootstrap::init)
[21:49:38] [main/INFO]: Searching for graphics cards...
[21:49:43] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=INTEL, name=Intel(R) UHD Graphics 620, version=DriverVersion=31.0.101.2111]
[21:49:43] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce MX150, version=DriverVersion=31.0.15.1748]
[21:49:43] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[21:49:43] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[21:50:54] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 3172 milliseconds
[21:51:34] [Render thread/INFO]: mixins.future.common.json:MixinMinecraft from mod (unknown)->@Accessor[FIELD_GETTER]::getCurrentFps()I should be static as its target is
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketFull(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketPosGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketLookGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketFull(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketPosGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketLookGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_746 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:220) ~[1.20.1-Fabric%200.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.4-1907.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:220) ~[1.20.1-Fabric%200.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector sendPacketFull(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V in blackout.mixins.json:MixinClientPlayerEntity from mod blackout failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap blackout-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:104) ~[meteor-client-0.5.4-1907.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:220) ~[1.20.1-Fabric%200.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	... 8 more

```

```
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketFull(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketPosGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketLookGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:35] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketFull(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketPosGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketLookGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/WARN]: @Redirect conflict. Skipping blackout.mixins.json:MixinClientPlayerEntity from mod blackout->@Redirect::sendPacketGround(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 1000, already redirected by mixins.future.common.json:entity.living.player.MixinEntityPlayerSP from mod (unknown)->@Redirect::f$g(Lnet/minecraft/class_634;Lnet/minecraft/class_2596;)V with priority 2147483647
[21:51:38] [Render thread/ERROR]: Minecraft has crashed!
```

**Comment by KassuK1** [comment]
not possible for us to fix and not worth it as Blackout has every feature you would use in future
